name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this if you want to trigger on a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Update and install Nginx
          sudo apt update
          sudo apt install -y nginx

          # Create directory and HTML file
          sudo mkdir -p /var/www/html/shubh
          echo '<!DOCTYPE html><html><head><title>Shubh\'s Page</title></head><body><h1>Hello, from Shubh!</h1></body></html>' | sudo tee /var/www/html/shubh/1.html
          
          # Restart Nginx
          sudo systemctl restart nginx
        EOF
